#!/bin/bash

set -ex

#
# builds our image with the arguments we need for labels
#

docker image build \
	--build-arg BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ") \
	--build-arg VCS_REF=$(git rev-parse --short HEAD) \
	-t $IMAGE_NAME .
