name: build
on: pull_request

jobs:
  build:
    name: docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: assign version for usage
        id: assign
        run: echo "::set-output name=version::$(git rev-parse --short HEAD)"
      - name: build the container
        run: bin/build-image.sh
        env:
          VERSION: ${{ steps.assign.outputs.version }}
          DOCKER_BUILDKIT: 1
