name: lint
on:
  pull_request:
    paths:
      - "**.md"
      - "**.yml"

jobs:
  prettier:
    runs-on: ubuntu-20.04
    name: prettier
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.1.0
        with:
          node-version: "14.x"
      - name: install prettier
        run: npm install -g prettier
      - name: run prettier
        run: prettier -c .
