name: lint
on:
  pull_request:
    paths:
      - "Dockerfile"

jobs:
  hadolint:
    runs-on: ubuntu-20.04
    name: hadolint
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: jbergstroem/hadolint-gh-action@v1.9.1
        with:
          error_level: 2
