name: lint
on:
  pull_request:
    paths:
      - "Dockerfile"

jobs:
  hadolint:
    runs-on: ubuntu-20.04
    name: hadolint
    steps:
      - uses: actions/checkout@v2.3.5
      - uses: jbergstroem/hadolint-gh-action@v1.8.0
        with:
          error_level: 2
