name: test
on: pull_request

jobs:
  build:
    name: test container
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3.1.0
      - name: assign version for usage
        id: assign
        run: echo IMAGE_VERSION="$(git rev-parse --short HEAD)" >> "$GITHUB_ENV"
      - name: build the container
        run: sh/build-image.sh
        env:
          VERSION: ${{ env.IMAGE_VERSION }}
      - name: download cli
        run: docker pull jbergstroem/mariadb-client-alpine:latest
      - name: install bash_unit
        env:
          BASH_UNIT_VERSION: 2.0.1
        run: |
          wget -q -O- https://github.com/pgrange/bash_unit/archive/refs/tags/v${{ env.BASH_UNIT_VERSION }}.tar.gz | tar xz --strip=1 -C . && \
          sudo mv bash_unit /usr/local/bin
      - name: run suite
        run: bash_unit test/*.sh
