name: test
on: pull_request

jobs:
  bats:
    name: bash_unit
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3.1.0
      - name: assign version for usage
        run: echo "::set-output name=version::$(git rev-parse --short HEAD)"
        id: assign
      - name: build the container
        run: sh/build-image.sh
        env:
          VERSION: ${{ steps.assign.outputs.version }}
          DOCKER_BUILDKIT: 1
      - name: install bash_unit
        env:
          BASH_UNIT_VERSION: 2.0.1
        run: |
          wget -q -O- https://github.com/pgrange/bash_unit/archive/refs/tags/v${{ env.BASH_UNIT_VERSION }}.tar.gz | tar xz --strip=1 -C . && \
          sudo mv bash_unit /usr/local/bin
      - name: run suite
        run: bash_unit test/*.sh
        env:
          IMAGE_VERSION: ${{ steps.assign.outputs.version }}
