name: test
on: pull_request

jobs:
  bats:
    name: bats
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3.0.2
      - name: assign version for usage
        run: echo "::set-output name=version::$(git rev-parse --short HEAD)"
        id: assign
      - name: build the container
        run: sh/build-image.sh
        env:
          VERSION: ${{ steps.assign.outputs.version }}
          DOCKER_BUILDKIT: 1
      - name: install
        run: |
          curl -L https://github.com/bats-core/bats-core/archive/v1.6.0.tar.gz | tar zx --strip=1 -C /tmp/ &&
          sudo /tmp/install.sh /usr/local
      - name: run suite
        run: sh/run-tests.bash
        env:
          VERSION: ${{ steps.assign.outputs.version }}
