name: build & test
on: pull_request

jobs:
  build:
    name: build container
    runs-on: ubuntu-20.04
    outputs:
      version: ${{ steps.assign.outputs.version }}
    steps:
      - uses: actions/checkout@v3.1.0
      - name: assign version for usage
        id: assign
        run: echo "name=version::$(git rev-parse --short HEAD) >> $GITHUB_OUTPUT"
      - name: build the container
        run: sh/build-image.sh
        env:
          VERSION: ${{ steps.assign.outputs.version }}
          DOCKER_BUILDKIT: 1
  test:
    name: run tests
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - uses: actions/checkout@v3.1.0
      - name: install bash_unit
        env:
          BASH_UNIT_VERSION: 2.0.1
        run: |
          wget -q -O- https://github.com/pgrange/bash_unit/archive/refs/tags/v${{ env.BASH_UNIT_VERSION }}.tar.gz | tar xz --strip=1 -C . && \
          sudo mv bash_unit /usr/local/bin
      - name: run suite
        run: bash_unit test/*.sh
        env:
          IMAGE_VERSION: ${{ needs.build.outputs.version }}
