name: test
on: pull_request

jobs:
  build:
    name: container e2e tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3.1.0
      - name: assign version for usage
        id: assign
        run: echo IMAGE_VERSION="$(git rev-parse --short HEAD)" >> "$GITHUB_ENV"
      - name: build the container
        run: sh/build-image.sh
        env:
          VERSION: ${{ env.IMAGE_VERSION }}
      - name: download cli
        run: docker pull jbergstroem/mariadb-client-alpine:latest
      - name: install bash_unit
        env:
          BU_VERSION: 2.0.1
          BU_BASEURL: https://github.com/pgrange/bash_unit/archive/refs/tags
        run: |
          wget -q -O- ${{ env.BU_BASEURL }}/v${{ env.BU_VERSION }}.tar.gz | tar xz --strip=1 -C . && \
          sudo mv bash_unit /usr/local/bin
      - name: run suite
        run: bash_unit test/*.sh
